<a href="https://colab.research.google.com/github/KY-39/platforma_udt/blob/main/%D0%91%D0%B8%D0%B1%D0%BB%D0%B8%D0%BE%D1%82%D0%B5%D0%BA%D0%B0_%D0%B1%D1%8B%D1%81%D1%82%D1%80%D1%8B%D1%85_%D0%B2%D1%8B%D1%87%D0%B8%D1%81%D0%BB%D0%B5%D0%BD%D0%B8%D0%B9_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## ООО "Университет Цифровых Технологий платформа 3"

# Библиотека быстрых вычислений NUMPY

# Уровень базовый

## Задание 1

импортируйте библиотеку numpy,  выведите на экран номер версии библиотеки

In [ ]:
import numpy as np

In [ ]:
print(np.__version__)

1.19.5


## Задание 2

создайте 2-х мерный nd-array их списка списков  

[[1, 2, 3, 4, 5], [2, 3, 4, 5, 6]]


* Выведите на печать исходный список
* Выведите на печать nd-array 
* Выведите на печать информацию о nd-array 
    - форму (shape), 
    - тип хранимых элементов, 
    - общее количество элементов


In [ ]:
data = [[1, 2, 3, 4, 5], [2, 3, 4, 5, 6]]
nd = np.array(data)
print(nd)

[[1 2 3 4 5]
 [2 3 4 5 6]]


In [ ]:
print('форма (shape) - ', nd.shape)
print('тип хранимых элементов - ', nd.dtype)
print('общее количество элементов - ', nd.size)

форма (shape) -  (2, 5)
тип хранимых элементов -  int64
общее количество элементов -  10


## Задание 3

создайте 
* нулевой вектор (вектор, содержащий только 0) размерностью 1 и размером 10, 
* нулевой вектор размерности 2 и размером 4х4
* создайте единичные вектора, форма которых совпадает с формой созданных нулевых векторов


In [ ]:
zero1 = np.zeros(shape=10)
zero2 = np.zeros(shape = (4, 4))

In [ ]:
ones1 = np.ones_like(zero1)
ones2 = np.ones_like(zero2)
ones2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## Задание 4

Создайте двумерную матрицу размером 10х10
 состоящую  из случайных целых чисел от 0 до 10


In [ ]:
matrix = np.random.randint(low=0, high=10, size=(10, 10))

In [ ]:
matrix

array([[2, 0, 5, 9, 4, 1, 6, 5, 1, 4],
       [1, 0, 6, 4, 7, 5, 9, 6, 1, 4],
       [2, 6, 9, 8, 7, 2, 2, 0, 6, 1],
       [2, 0, 6, 7, 6, 9, 2, 3, 4, 5],
       [4, 0, 7, 6, 6, 1, 3, 6, 7, 0],
       [2, 2, 3, 5, 0, 4, 1, 5, 7, 7],
       [7, 4, 6, 2, 8, 3, 5, 1, 5, 6],
       [0, 5, 8, 7, 0, 3, 5, 5, 7, 0],
       [2, 4, 3, 3, 3, 8, 7, 6, 4, 9],
       [6, 0, 7, 1, 6, 7, 3, 3, 8, 7]])

## Задание 5

Создайте матрицу размером 10*10, все элементы которой равны 9

In [ ]:
matrix1 = np.ones(shape = (10, 10)) * 9

In [ ]:
matrix1

array([[9., 9., 9., 9., 9., 9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

# Уровень Основной

## Задание 1

Создайте вектор размерности 1 состоящий из чисел от 0 до 10. Преобразуйте его в 2-х мерный вектор - строку. Выведите результат.

In [ ]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
y = x.reshape((1, -1))
y

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

## Задание 2

Создайте вектор размерности 1 состоящий из чисел от 0 до 10. Преобразуйте его в 2-х мерный вектор - столбец. Выведите результат.

In [ ]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
y = x.reshape((-1, 1))
y

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

## Задание 3

без использования циклов создайте nd-array размерности 1 состоящий из чисел от 10 до 99

In [ ]:
x = np.arange(start = 10 ,stop = 100)

In [ ]:
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

## Задание 4

без использования циклов создайте nd-array размерности 1, состоящий из чисел от 100 до 0 с шагом 2.

In [ ]:
x = np.arange(start=100, stop=-2, step=-2)

In [ ]:
x

array([100,  98,  96,  94,  92,  90,  88,  86,  84,  82,  80,  78,  76,
        74,  72,  70,  68,  66,  64,  62,  60,  58,  56,  54,  52,  50,
        48,  46,  44,  42,  40,  38,  36,  34,  32,  30,  28,  26,  24,
        22,  20,  18,  16,  14,  12,  10,   8,   6,   4,   2,   0])

## Задание 5 

создайте вектор размерности 1, состоящий из чисел от 0 до 99.  Без использования циклов разверните nd-array так, чтобы порядок следования изменился от последнего к первому (было 0, 1….99; стало 99, 98..1, 0)


In [ ]:
x = np.arange(0, 100, 1)

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [ ]:
x[::-1]

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

## Задание 6

без использования циклов создайте матрицу размера 5x5 состоящую из случайных чисел взятых из нормального распределения с mu = 0 и sigma=1

In [ ]:
x = np.random.normal(loc=0, scale=1, size=(5, 5))

In [ ]:
x

array([[-1.13020488, -1.79637184, -0.14902254, -0.24186665,  0.61752553],
       [-0.86474745,  0.81255554, -0.07179057,  0.18499922,  1.91100944],
       [-0.76785095, -0.74600963, -1.94688621,  0.95338494, -1.51710996],
       [-1.39992745, -0.08952398, -1.34860438,  0.36177936, -1.56363399],
       [ 0.7996937 ,  2.0972506 ,  0.46944454, -1.79894482,  0.44469942]])

## Задание 7

создайте одномерный вектор  размером 16 и заполните его числами от 0 до 15  Измените его форму так, чтобы у итоговой таблицы стало 4 строки и 4 столбца.

In [ ]:
x = np.arange(start=0, stop=16, step=1)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
y = x.reshape((4, 4))
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

## Задание 8

С помощью reshape измените размерность единичной матрицы (8,8) на (8,8,1), а затем с помощью concatenate объедините её саму с собой вдоль каждой из осей по отдельности. Посмотрите все три результата с помощью shape для каждого случая объединения.

In [ ]:
x = np.eye(8)
x

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
x = x.reshape(8,8,1)
x.shape

(8, 8, 1)

In [ ]:
y = np.concatenate((x, x), axis = 0)
y.shape

(16, 8, 1)

In [ ]:
y = np.concatenate((x, x), axis = 1)
y.shape

(8, 16, 1)

In [ ]:
y = np.concatenate((x, x), axis = 2)
y.shape

(8, 8, 2)

# Уровень Продвинутый

## Задание 1

создайте двумерную матрицу размером 10x10, заполненную случайными целыми числами в интервале от -10 до 10. 
* напечатайте матрицу
* найдите сумму квадратов всех элементов матрицы с помощью циклов
* найдите сумму квадратов всех элементов матрицы без использования циклов, исключительно с помощью матричных операций
* найдите среднее значение всех элементов nd-array c помощью циклов
* найдите среднее значение всех элементов без использования циклов, с помощью матричных операций
* напишите свои выводы


In [ ]:
x = np.random.randint(-10, 10, size=(10, 10))
x

array([[ -4,  -2,   2,   4,   6,  -1,  -4,  -5,   3,   8],
       [ -1,   5,  -5,  -7,   7,  -5,   3,   2,  -6,   1],
       [  7,   5,   4,   9, -10,   3,   1,   3,   7,  -7],
       [  5,  -8,  -1,   8,   4,  -4,   6,   4,   8,  -8],
       [  1,   1,   8,  -6,   6,  -4, -10,  -4,   3,   7],
       [ -7,   2,   5,   4,  -2, -10,  -3,   0,  -3,  -6],
       [ -3,  -7,  -6,  -6,   5,   0,   3,  -5,  -3,  -7],
       [ -8,   3,   0, -10,   8,  -4,  -8,   1,   8,   9],
       [  6,   1,   9,  -2,   3,   4,   0,   8,   2,   7],
       [  3,  -5,   4,   6,  -5,   1,  -9,   7,   6,  -2]])

In [ ]:
sum = 0

for i in range(10):
    for j in range(10):
        sum += x[i, j] ** 2

sum

3005

In [ ]:
(x * x).sum()

3005

In [ ]:
sum = 0

for i in range(10):
    for j in range(10):
        sum += x[i, j]

sum / (10 * 10)

0.33

In [ ]:
x.mean()

0.33

## Задание 2

создайте матрицу размером 5х5 так, чтобы на главной диагонали было число 10, а в остальных ячейках -3

In [ ]:
x = np.eye(5)
x

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
y = x * 13 - 3
y

array([[10., -3., -3., -3., -3.],
       [-3., 10., -3., -3., -3.],
       [-3., -3., 10., -3., -3.],
       [-3., -3., -3., 10., -3.],
       [-3., -3., -3., -3., 10.]])

## Задание 3

создайте единичную матрицу размером 5x5, так, чтобы все значения в первой строке (по индексу в нулевой) равнялись 0, во второй  1, в третьей  2 и т.д.


In [ ]:
x = np.zeros(shape=(5, 5))
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
y = x + np.arange(5).reshape(-1, 1)
y

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

# Уровень Профессиональный

## Задание 1

выведите на печать “таблицу умножения” - матрицу размером 9x9

[[ 1 2 3 4 5 6 7 8 9]

[ 2 4 6 8 10 12 14 16 18]

[ 3 6 9 12 15 18 21 24 27]

[ 4 8 12 16 20 24 28 32 36]

[ 5 10 15 20 25 30 35 40 45]

[ 6 12 18 24 30 36 42 48 54]

[ 7 14 21 28 35 42 49 56 63]

[ 8 16 24 32 40 48 56 64 72]

[ 9 18 27 36 45 54 63 72 81]]

использовать циклы нельзя, только матричные операции

In [ ]:
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x.reshape((1, -1)) * x.reshape((-1, 1)) 

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 9, 18, 27, 36, 45, 54, 63, 72, 81]])

## Задание 2

создайте матрицу размером 10x10, на главной диагонали которой будут числа от 1 до 10, остальные значения равны -1

In [ ]:
x = np.eye(10)
x

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
y = x * np.arange(2, 12).reshape((-1, 1)) - 1
y

array([[ 1., -1., -1., -1., -1., -1., -1., -1., -1., -1.],
       [-1.,  2., -1., -1., -1., -1., -1., -1., -1., -1.],
       [-1., -1.,  3., -1., -1., -1., -1., -1., -1., -1.],
       [-1., -1., -1.,  4., -1., -1., -1., -1., -1., -1.],
       [-1., -1., -1., -1.,  5., -1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.,  6., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1., -1.,  7., -1., -1., -1.],
       [-1., -1., -1., -1., -1., -1., -1.,  8., -1., -1.],
       [-1., -1., -1., -1., -1., -1., -1., -1.,  9., -1.],
       [-1., -1., -1., -1., -1., -1., -1., -1., -1., 10.]])

## Задание 3

создайте матрицу размером 10*10, заполненную случайными целыми числами в диапазоне от [-10 ,  +10], границы включены.  найдите
* Максимальный элемент матрицы
* Минимальный элемент матрицы
* сумму всех элементов матрицы
* среднее всех элементов матрицы
* суммы по строкам и по столбцам
* сумму и количество  всех элементов больших нуля
* среднее всех элементов меньших нуля


In [ ]:
x = np.random.randint(-10, 11, (10, 10))
x

array([[ -7,   4,  -4,  -5,  -4,   1,   3,   3,   0,  -7],
       [ -3,   1,   1,  -9,  -5,   9,   2,   1,   4,  -6],
       [ -3,   3,   4,   0,   3, -10,  -7,   9,  -3,   1],
       [ -4,   3,  -5,  -5,   4,   2,  10,   8,  -8,   8],
       [ -5,   0,   9,  -4,   7,  -1,  -4,  -7,   4,   5],
       [  9,   9,  -6,   2,   2,   3,  -2,   9,  -2,   5],
       [  9,   6,   6,  -8,  -8,   0,   1,  -8,   2,  -4],
       [  7,   3,  -9,  -5,  -3,  -8,  10,   5,  10, -10],
       [ -9,   1,  -5, -10,   6,   1,   1,   6,  -5,   4],
       [ -8,  -8,  -2,  -9, -10,  -5,  -8,  -2,   3,   9]])

In [ ]:
print(f'максимальный элемент матрицы {x.max()}')
print(f'минимальный элемент матрицы {x.min()}')
print(f'сумма всех элементов матрицы {x.sum()}')
print(f'среднее значение элементов матрицы {x.mean()}')

максимальный элемент матрицы 10
минимальный элемент матрицы -10
сумма всех элементов матрицы -32
среднее значение элементов матрицы -0.32


In [ ]:
x.sum(axis=0)

array([-14,  22, -11, -53,  -8,  -8,   6,  24,   5,   5])

In [ ]:
x.sum(axis=1)

array([-16,  -5,  -3,  13,   4,  29,  -4,   0, -10, -40])

In [ ]:
(x > 0).sum()

50

In [ ]:
x[x > 0].sum()

238

In [ ]:
x[x < 0].mean()

-5.869565217391305